core/src/main/scala/com/github/tminglei/slickpg/array/PgArrayJdbcTypes.scala
core/src/main/scala/com/github/tminglei/slickpg/utils/PgCommonJdbcTypes.scala
core/src/main/scala/com/github/tminglei/slickpg/utils/SimpleArrayUtils.scala
core/src/main/scala/com/github/tminglei/slickpg/utils/package.scala
src/main/scala/com/github/tminglei/slickpg/PgArraySupport.scala
src/main/scala/com/github/tminglei/slickpg/PgEnumSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgHStoreSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgJsonSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgLTreeSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgNetSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgArgonautSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgDate2Support.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgDateSupport2bp.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgDateSupportJoda.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgJson4sSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgPlayJsonSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgPostGISSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgSprayJsonSupport.scala

Add static sql type mapping support
How to use it?
Declare your custmization postgres driver as below:
```scala
import slick.driver.PostgresDriver
import com.github.tminglei.slickpg._
trait MyPostgresDriver extends PostgresDriver
with PgArraySupport
with PgDateSupportJoda
with PgRangeSupport
with PgHStoreSupport
with PgPlayJsonSupport
with PgPostGISSupport {
override lazy val Implicit = new ImplicitsPlus {}
override val simple = new SimpleQLPlus {}
//////
trait ImplicitsPlus extends Implicits
with SimpleArrayPlainImplicits
with JodaDateTimePlainImplicits
with SimpleRangePlainImplicits
with SimpleHStorePlainImplicits
with PlayJsonPlainImplicits
with PostGISPlainImplicits
trait SimpleQLPlus extends SimpleQL with ImplicitsPlus
}
object MyPostgresDriver extends MyPostgresDriver
```
Then add …

Static sql

---

.travis.yml
core/src/main/scala/com/github/tminglei/slickpg/json/PgJsonExtensions.scala
src/main/scala/com/github/tminglei/slickpg/PgJsonSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgArgonautSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgJson4sSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgPlayJsonSupport.scala
src/main/scala/com/github/tminglei/slickpg/addon/PgSprayJsonSupport.scala
src/test/scala/com/github/tminglei/slickpg/MyPostgresDriver.scala
src/test/scala/com/github/tminglei/slickpg/PgJsonSupportTest.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgArgonautSupportTest.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgJson4sSupportTest.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgPlayJsonSupportTest.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgSprayJsonSupportTest.scala

1) Add jsonb support
2) Add more json operators/functions support
**Note: to keep compatible, `jsonb` support is not on by default.**
You can enable it with config like this:
```scala
trait MyPostgresDriver extends ExPostgresDriver
...
with PgJsonSupport
with PgSearchSupport {
override val pgjson = "jsonb"
...
```

Enhance json support for postgres 9.4

---

project/Build.scala

There's a binary incompatibility in the render() method between json4s 3.2.10 and 3.2.11 json4s/json4s#212 
Other major libraries like spray are already using json4s 3.2.11, which makes it difficult to use them alongside slick-pg because of this incompatibility.  Can you do a quick release upgrading to json4s 3.2.11?  It has no impact on the functionality you are using, there is just a change of render method signature where the new implicit parameter is supplied a default value, so it won't break any slick-pg code.

Upgrade to json4s 3.2.11

---

src/main/scala/com/github/tminglei/slickpg/addon/PgDate2Support.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgDate2SupportTest.scala

PostgreSQL supports two special date/time input values: `infinity` and `-infinity`, which are respectively later and earlier than all other time stamps.  See [manual section 8.5.1.4, Special Date/Time Values](http://www.postgresql.org/docs/9.4/interactive/datatype-datetime.html#AEN6039)
Currently, if slick-pg receives one of these values from a server it fails with an exception.  This patch adds the relevant support to slick-pg's `java.time` (three-ten) support features.  When these values are received from a server, they are interpreted as being one of the maximum or minimum possible `Date`, `LocalDateTime`, `OffsetDateTime` or `ZonedDateTime` values as defined by constants in the Java library, using UTC for types that represent offsets or timezones.
Conversely, when such a minimum- or …

Add date/timestamp values "infinity" and "-infinity" to threeten support

---

project/Build.scala

Argonaut 6.1 is binary incompatible with 6.0 because of a scalaz change. 6.1 is
also the latest stable version.

Bump argonaut to version 6.1

---

README.md

Using `val` causes the error described in this issue (https://github.com/tminglei/slick-pg/issues/141). Switching it from `val` to `def` fixed it for me.

Fixes documentation error

---

examples/play-slick-example/build.sbt

This will pull in Slick version `3.0.1`, which contains a fix for the custom Postgres driver failing to load when running Play in dev mode.
Fixes #199

Bump play-slick version in Play example

---

project/Build.scala

Add circe module to root project's aggregate to fix #265 . I think it's the reason that the circe-json module is missing in maven repo.

Hope for fix #265

---

examples/play-slick-example/build.sbt
examples/play-slick-example/conf/logback.xml
examples/play-slick-example/project/plugins.sbt

Basic PR updating to latest Play and drivers.  Update example/play-slick-example to use Play 2.5.1, update play-slick and play-slick-evolutions to use 2.0.0 and update slick-pg drivers to use 0.12.1.

Update example/play-slick-example to use Play 2.5.1

---

src/main/scala/com/github/tminglei/slickpg/Languages.java
src/main/scala/com/github/tminglei/slickpg/PgEnumSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgCustomEnumSupportSuite.scala

There's quite a number of views on how you should provide enum or enum-like capabilities in Scala. The built in Enumeration type is an obvious option, but I've seen case objects and Java enums used in production Scala code as well.
This makes mapping these types to Postgres enums in Slick impossible without a DTO-ish Enumeration you can use to construct the JDBC mappings. So in this PR, I add a new `PgCustomEnumSupport` trait which can be mixed in to your driver to allow a custom mapping from a type T to String and back from String to type T.
Let me know what you think.

Allowing custom types to be mapped to Postgres enums

---

README.md
core/src/main/scala/com/github/tminglei/slickpg/ExPostgresDriver.scala
core/src/test/scala/com/github/tminglei/slickpg/PgUpsertSuite.scala
project/Build.scala

Currently the native upsert generator does not properly quote the column names in all places. As a result any table with a reserved key word (e.g. `end`) as a column name will throw a syntax error when executed:
```
org.postgresql.util.PSQLException: ERROR: syntax error at or near "end"
```
Note the difference between the insert and upsert statements for an insert vs an upsert of `Bean2(100, 1, 2)` as defined in the new test cases but without this change:
```
cala> beanInsert.statements
res2: Iterable[String] = Vector(insert into "test_tab_upsert2" ("id","start","end")  values (?,?,?))
scala> beanUpsert.statements
res3: Iterable[String] = Vector("insert into "test_tab_upsert2" (id,start,end) values (?,?,?) on conflict ("id") do update set "start"=EXCLUDED."start","end"=EXCLUDED."end" ") …
```

Add support for upsert with tables containing keyword column names

---

README.md
core/src/main/scala/com/github/tminglei/slickpg/lobj/LargeObjectStreamingDBIOAction.scala
core/src/main/scala/com/github/tminglei/slickpg/lobj/LargeObjectSupport.scala
core/src/main/scala/com/github/tminglei/slickpg/lobj/README.md
core/src/test/scala/com/github/tminglei/slickpg/lobj/LargeObjectSupportSuite.scala

Hello,
I was recently working on a side project using Slick, Postgres, and Play and needed to stream LargeObject instances directly from a Postgres database down to a client. After a large amount of reading and scouring of the Internet, I decided to roll my own action for doing this. It allows you to open an InputStream on a Postgres LargeObject and stream it down to a client. Basically, running the action with `database.stream` produces a `DatabasePublisher[Array[Byte]]` instance. From the controller layer of my application, I just do this to open a chunked reactive stream down to the client
```
Ok.chunked(Source.fromPublisher(someFunctionThatProducesTheDatabasePublisher())).
as("some/mime-type").
withHeaders(
"Content-Disposition" ->"attachment; filename=some-file.txt"
)
```
So, at this …

Postgres LargeObject reactive streaming action

---

core/src/main/scala/com/github/tminglei/slickpg/geom/PgPostGISExtensions.scala

Hello,
1. `ST_Distance_Sphere` has been deprecated and we should now use `ST_DistanceSphere`
> Changed: 2.2.0 In prior versions this used to be called ST_Distance_Sphere
http://postgis.net/docs/ST_DistanceSphere.html
2. `ST_DistanceSpheroid` was not mapped.
I don't know how you want to handle this deprecation cases? Shall I add new methods that map on `ST_Distance_Sphere` and `ST_Distance_Spheroid`?

Follow up on PostGIS deprecation and add missing function mapping

---

core/src/main/scala/com/github/tminglei/slickpg/lobj/LargeObjectStreamingDBIOAction.scala

Fixed issue with large object streaming where emitting empty byte arrays could cause a stream to terminate prematurely.
I've found this to only occur when streaming a large object via a chunked response on the Play framework. Apparently this is a feature of Akka HTTP too (if I'm not mistaken). See this issue for more details: https://github.com/playframework/playframework/issues/6750

Fixed issue with empty byte arrays on large object streams

---

addons/play-json/src/main/scala/com/github/tminglei/slickpg/PgPlayJsonSupport.scala
addons/play-json/src/test/scala/com/github/tminglei/slickpg/PgPlayJsonSupportSuite.scala

postgres does not allow this character in their json/jsonb types so we need to remove it before it hits the db.
This addresses #347

Remove all \u0000 characters in encoded json

---

README.md

There is no ExPostgresDriver mentioned in README.md anymore. It is superseded by ExPostgresProfile.

Use ExPostgresProfile in README.md

---

core/src/main/scala/com/github/tminglei/slickpg/date/PgDateJdbcTypes.scala
src/test/scala/com/github/tminglei/slickpg/PgDate2SupportSuite.scala

Closes #359
Added a test case with `Option` columns, for the `PgDate2SupportSuite`. 
Without the fix at `GenericDateJdbcType`, you can reproduce the reported error.

Fixed the GenericDateJdbcType when mapping `Option[Duration]` column

---

src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgRangeSupportSuite.scala

Fix for #302 
- Adds java.time mappings to PgRangeSupport that match mappings sepcified at [Table 1 from Oracle Blog](http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html)
- Adds mapping for tstzrange

Add java.time support to Range

---

examples/codegen-customization/build.sbt
examples/codegen-customization/codegen/src/main/scala/demo/Config.scala
examples/codegen-customization/codegen/src/main/scala/demo/CustomizedCodeGenerator.scala
examples/codegen-customization/codegen/src/main/scala/demo/MyPostgresDriver.scala
examples/codegen-customization/docker-compose.yml
examples/codegen-customization/project/build.properties
examples/codegen-customization/project/plugins.sbt
examples/codegen-customization/src/sql/create-tables.sql
examples/codegen-customization/src/sql/populate-tables.sql

Updated `codegen-customization` example.
- In latest slick-pg, codegen for collection types don't work properly. its `rawType` generates `scala.collection.Seq` for list types and `scala.collection.Map` for map types, also it doesn't reveal any generic type info. As previous example checks sqlType only if rawType is `String`, it doesn't work. I fixed that to check sqlType first for collection types and then check other types.
- added `docker-compose.yml`, you can just run `docker-compose up` and then run example. and check ui by `dockerhost:8081` on browser
- and updated dependencies

update codegen-customization example

---

addons/jts_lt/src/main/scala/com/github/tminglei/slickpg/PgPostGISSupport.scala
addons/jts_lt/src/test/resources/logback.xml
addons/jts_lt/src/test/scala/com/github/tminglei/slickpg/PgPostGISSupportSuite.scala
build.sbt

Ownership of JTS has been transfered to locationtech (https://github.com/locationtech/jts). Unfortunately the package names have been changed, so it's not sufficient to merely change the groupId. This PR adds a new addon which is identical to the existing jts addon, except it uses the new locationtech version of JTS. Please let me know if an alternative approach is preferred (e.g. just changing the version used in the existing jts addon)

Add support for locationtech's JTS library

---

build.sbt
core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala
src/main/scala/com/github/tminglei/slickpg/PgDate2Support.scala

this updates binary dep, adjusts for new parameter in createTable, and removes newly added support for java.time.* since it already exists and we'd like to preserve compatibility with existing formats

update to slick 3.3.0

---

.travis.yml
addons/jawn/src/main/scala/com/github/tminglei/slickpg/PgJawnJsonSupport.scala
addons/jawn/src/test/scala/com/github/tminglei/slickpg/PgJawnJsonSupportSuite.scala
build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/com/github/tminglei/slickpg/PgHStoreSupport.scala

* upgrade some dependencies
* update some Java conversions due to Scala 2.13 removing deprecated WrapAsJava, WrapAsScala
* uses circe 0.12.0-M3 while full release is awaited
* jawn-parser - use latest typelevel version (taken over from spire-math)

WIP: some changes to support scala 2.13

---

.gitignore
build.sbt
project/build.properties
project/plugins.sbt

* SBT was updated to 1.3.7, so I had to change the description of modules in the build.sbt and makePomConfiguration initialisation
* GPG plugin was updated to 2.0.1, now useGpg := true by default
* changes in .gitignore for vscode

Update sbt to 1.3.7

---

build.sbt

Current version contains [a serious security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2020-13692) fixed in the latest version
Upgrading protects users who import the vulnerable version transitively

Upgrade postgresql JDBC driver

---

core/src/main/scala/com/github/tminglei/slickpg/utils/PlainSQLUtils.scala
core/src/main/scala/com/github/tminglei/slickpg/utils/SimpleArrayUtils.scala
src/test/scala/com/github/tminglei/slickpg/PgArraySupportSuite.scala

Thanks for this library!
This PR fixes an issue with redundant escaping of quotes (`''`) in plain SQL support for `SetParameter`. Quotes in plain arrays are escaped twice. Once by `escaped` method and the second time by (I presume) `java.sql.PreparedStatement` causing a redundant quote being inserted.
The issue shows when extending tests. For `Some(List("tewe", "ttt", "apostrophe'")`:
```
[info] - Array Plain SQL support *** FAILED ***
[info]   "apostrophe'[]" did not equal "apostrophe'[']" (PgArraySupportSuite.scala:247)
```
It is fixed by leaving escaping up to `PreparedStatement` when serialized as a parameter (`SetParameter`) and escaping explicitly when inlined as per https://github.com/tminglei/slick-pg/issues/473.

Fix escaping quotes in string arrays

---

src/main/scala/com/github/tminglei/slickpg/PgJsonSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgJsonSupportSuite.scala

In #348 and #475, serde-specific artifacts (circe, play-json, etc.) were updated to strip `\u0000` characters (which are disallowed for json/jsonb values in Postgres) - this PR updates the default `PgJsonSupport` to also perform the same stripping logic.

Remove all \u0000 characters from JSON strings in simple json support

---

README.md

The code wasn't compiling, after some Google search I noticed it should be `JdbcCapabilities` instead of `JdbcProfile`

fix readme instructions

---

core/src/main/scala/com/github/tminglei/slickpg/utils/PgTokenHelper.scala
src/main/scala/com/github/tminglei/slickpg/PgCompositeSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala

There are bugs when using `()[]` characters in an array column in a composite type.
This PR reproduces, I'll poke around at fixing but if I don't get it done than hopefully someone else can take it from here.
For the failing test case, the column that needs to be parsed is
`(2,x2,"{""xxx(yyy)zz,z"",u(vv)w,x=1&y=2&[INSERT_DEVICE_ID_HERE]&z=3}","{""\\""t""}","(get(""A"") + get(""A"")).ok","call(A, B).ok")`
which tokenizes as
`Open((), Chunk(2), Comma, Chunk(x2), Comma, Marker("), Open({), Marker(""), Chunk(xxx), Open((), Chunk(yyy), Close()), Chunk(zz), Comma, Chunk(z), Marker(""), Comma, Chunk(u), Open((), Chunk(vv), Close()), Chunk(w), Comma, Chunk(x=1&y=2&), Open([), Chunk(INSERT_DEVICE_ID_HERE), Close(]), Chunk(&z=3), Close(}), Marker("), Comma, Marker("), Open({), Marker(""\\""), …

Reproduce composite parsing bug

---

core/src/main/scala/com/github/tminglei/slickpg/utils/PgTokenHelper.scala

Basically reverting https://github.com/tminglei/slick-pg/commit/79f39bacdc4faff0fbc12dec1dd65b66b1694f3e from #512 
`soFar` really does need to be a collection with efficient `.last` and `.append`, because otherwise every `:+` is its own O(n) operation. We (at tubi.tv) found that the performance hit (with `List`) was too severe for production usage.
Alternatively if `List` is used then the recursive function needs to be refactored to [build `soFar` in reverse](https://github.com/tminglei/slick-pg/compare/master...adRise:no-shame#)

Token smushing in O(n)

---

core/src/main/scala/com/github/tminglei/slickpg/trgm/PgTrgmSupport.scala

This fixes a minor issue that I noticed when trying to use `PgTrgmImplicits` and `PgStringImplicits` in the same trait.
For example:
```scala
object BrokenProfile extends PgTrgmSupport with PgStringSupport with PostgresProfile {
trait Implicits extends PgTrgmImplicits with PgStringImplicits
}
```
produces the compiler error:
```
[error]   implicit def pgStringColumnExtensionMethods(c: com.github.tminglei.slickpg.trgm.BrokenProfile.api.Rep[String]): com.github.tminglei.slickpg.trgm.BrokenProfile.PgTrgmColumnExtensionMethods[String] (defined in trait PgTrgmImplicits) and
[error]   implicit def pgStringColumnExtensionMethods(c: com.github.tminglei.slickpg.trgm.BrokenProfile.api.Rep[String]): com.github.tminglei.slickpg.trgm.BrokenProfile.PgStringColumnExtensionMethods[String] (defined in …
```

Rename implicit defs in PgTrmImplicits to avoid collision with PgStringImplicits

---

core/src/main/scala/com/github/tminglei/slickpg/search/PgSearchExtensions.scala
core/src/main/scala/com/github/tminglei/slickpg/search/README.md
src/test/scala/com/github/tminglei/slickpg/PgSearchSupportSuite.scala

Added missing tsQuery <-> tsQuery -> tsQuery phrase operator

Add tsQuery <-> tsQuery -> tsQuery

---

README.md
build.sbt

**Update Postgres JDBC Driver to 42.4.1**
Current 42.2.19 version of Postgres JDBC driver has vulnerability ([CVE-2022-21724](https://www.cvedetails.com/cve/CVE-2022-21724), [mvnrepository slick-pg 0.20.3](https://mvnrepository.com/artifact/com.github.tminglei/slick-pg_2.12/0.20.3)).

Update vulnerable Postgres JDBC Driver; jump to v0.20.4

---

core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala
core/src/test/scala/com/github/tminglei/slickpg/PgAutoIncSeqColumnSuite.scala

It fixes #601 
This PR adds 3 new column options to `ExPostgresProfile`:
- `AutoIncSeq` - flag that indicates that an auto incrementing for an AutoInc column will be done by explicitly creating a sequence.
- `AutoIncSeqName` - name of the sequence which is generated for an AutoIncSeq column. It overrides the default sequence name: `$schemaName.$tableName_$columnName_seq`.
- `AutoIncSeqFn` - Function that is used for generating the next value for an AutoIncSeq column. Example: `AutoIncSeqFn(nextVal => s"'Prefix' || $nextVal")` will be converted to `"DEFAULT 'Prefix' || nextval('$autoIncSeqName'::regclass)"`
Examples of usage:
```scala
def id = column[String]("id", O.AutoInc, O.AutoIncSeq, O.PrimaryKey)
...
def id = column[String]("id", O.AutoInc, O.AutoIncSeq, O.AutoIncSeqName("id_seq"), …
```

Add support an auto incrementing by explicitly creating a sequence

---

build.sbt

Should fix #586 upon publishing.

Rollback scala-parser-combinators to 1.1.2

---

build.sbt

Master branch has removed references to 2.11 and 2.12, so these splits are not needed anymore. Ran into them while attempting to see how much was needed to support scala 3 off the slick-milestone.

Remove split dependencies for scala < 2.13

---

addons/argonaut/src/main/scala/com/github/tminglei/slickpg/PgArgonautSupport.scala
addons/circe-json/src/main/scala/com/github/tminglei/slickpg/PgCirceJsonSupport.scala
addons/jawn/src/main/scala/com/github/tminglei/slickpg/PgJawnJsonSupport.scala
addons/joda-time/src/main/scala/com/github/tminglei/slickpg/PgDateSupportJoda.scala
addons/json4s/src/main/scala/com/github/tminglei/slickpg/PgJson4sSupport.scala
addons/jts/src/main/scala/com/github/tminglei/slickpg/PgPostGISSupport.scala
addons/jts_lt/src/main/scala/com/github/tminglei/slickpg/PgPostGISSupport.scala
addons/play-json/src/main/scala/com/github/tminglei/slickpg/PgPlayJsonSupport.scala
addons/spray-json/src/main/scala/com/github/tminglei/slickpg/PgSprayJsonSupport.scala
core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala
core/src/main/scala/com/github/tminglei/slickpg/str/PgStringSupport.scala
core/src/main/scala/com/github/tminglei/slickpg/trgm/PgTrgmSupport.scala
core/src/main/scala/com/github/tminglei/slickpg/window/PgWindowFuncCore.scala
src/main/scala/com/github/tminglei/slickpg/PgArraySupport.scala
src/main/scala/com/github/tminglei/slickpg/PgDate2Support.scala
src/main/scala/com/github/tminglei/slickpg/PgDateSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgHStoreSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgJsonSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgLTreeSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgNetSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala
src/main/scala/com/github/tminglei/slickpg/PgSearchSupport.scala

Give all public implicit def/val explicit type annotations which is required for compilation in scala 3

Scala 3 explicit implicits

---

addons/joda-time/src/test/scala/com/github/tminglei/slickpg/PgDateSupportJodaSuite.scala
core/src/main/scala/com/github/tminglei/slickpg/date/PgDateExtensions.scala
core/src/main/scala/com/github/tminglei/slickpg/date/README.md
src/test/scala/com/github/tminglei/slickpg/PgDate2SupportSuite.scala
src/test/scala/com/github/tminglei/slickpg/PgDateSupportSuite.scala

I don't know what your take is on functions that're introduced in versions of postgres > 11 - I didn't spot anything similar in the repo already - but this is a pretty handy one, so I thought I might as well give it a shot.

Add support for date_bin (available in postgres >= 14)

---

src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala

Encountered `(real_world_example` whole working on a project.
After writing a fix locally and adding tests I uncovered multiple other instances of array deserialization issues when inside a custom type.
may be related to https://github.com/tminglei/slick-pg/issues/504
These seem like the start of a deserialization vulnerability, adding a null into lists is very unusual?

Add examples of deserialization issues

---

build.sbt

Does the same as #587 for Scala 2.x, in order to prevent #586 and fix #705.

Rollback scala-parser-combinators to 1.1.2 on Scala 2.x

---

addons/circe-json/src/main/scala/com/github/tminglei/slickpg/PgCirceJsonSupport.scala

Modify Circe addon to use a compact JSON representation when sending stuff to the DB. Sending JSON pretty printed, with a multi-line representation, can result in some overhead. Other addons are using a compact representation as well, so I assume this was just an oversight.

Use compact JSON representation in Circe addon
