tminglei/slick-pg

core/src/main/scala/com/github/tminglei/slickpg/utils/PgTokenHelper.scala
src/test/scala/com/github/tminglei/slickpg/PgArraySupportTest.scala

it would generate a bad array literal

fix array escaping given an empty string or curly brace

---

project/Build.scala

Just upgrading to the last Scala versions.
Best,
Nicolas

Upgrade to Scala 2.11.6 & 2.10.5

---

src/main/scala/com/github/tminglei/slickpg/addon/PgDate2Support.scala
src/test/scala/com/github/tminglei/slickpg/addon/PgDate2SupportSuite.scala

This only works for reading `infinity` values out of the database, not for inserting. I'm not sure how that would be done, but this is at least the first half of getting to there.

Add +/-infinity support for plain SQL select queries.

---

src/test/scala/com/github/tminglei/slickpg/addon/PgDate2SupportSuite.scala

Includes insertion of infinity literals.  I estimate it is unsafe to combine the MIN and MAX values into one query and test only half of each, since the only difference between `infinity` and `-infinity` is one character that seems a likely source of an error and thus ought to be checked for.

Test all MIN/MAX ↔ ±infinity plain-sql combinations

---

project/Build.scala

Upgrading to last slick version.

upgrade to slick 3.0

---

src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala

I'm not sure what the fix is but if you have any ideas what the problem is I would greatly appreciate any information as I'm trying to implement a feature that uses this at the moment.
It breaks in the slick-pg internals in an unescape method.
Thank you!

Added failing test case for a simple composite type

---

project/Build.scala

Upgrade Slick to 3.1.0-RC3

---

project/Build.scala

slik 3.1.0

---

core/src/main/scala/com/github/tminglei/slickpg/array/PgArrayJdbcTypes.scala
src/test/scala/com/github/tminglei/slickpg/PgArraySupportSuite.scala

1) change `basedOn` to `mapTo`
2) statically check built-in support types

Array support enhancement

---

src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgRangeSupportSuite.scala

support infinite (unbounded) for range support (fix #234)

---

addons/play-json/src/test/scala/com/github/tminglei/slickpg/PgPlayJsonSupportSuite.scala

Work is based on the updated test case for Spray (provided by @tminglei at https://github.com/tminglei/slick-pg/commit/f1cf25536887b046f0c4c020932ca16dcf4f0aa8).

add test case for MappedJdbcType of `PlayJSON` JsValue <-> bean class

---

src/main/scala/com/github/tminglei/slickpg/PgEnumSupport.scala
src/test/scala/com/github/tminglei/slickpg/PgEnumSupportSuite.scala

Fix issue when `enumToString` is not just `_.toString` and filtering by enum causes invalid SQL

Fix valueToSQLLiteral for custom enum

---

core/src/main/scala/com/github/tminglei/slickpg/geom/PgPostGISExtensions.scala

Keep access to the deprecated PostGIS functions

---

README.md

Here are some comments on the readme to document the OffsetDateTime support.
Comments Welcome

Documentation for OffsetDateTime

---

addons/argonaut/src/main/scala/com/github/tminglei/slickpg/PgArgonautSupport.scala
addons/argonaut/src/test/scala/com/github/tminglei/slickpg/PgArgonautSupportSuite.scala
project/Build.scala

Argonaut 6.2 is not binary compatible with 6.1.

Support argonaut 6.2

---

addons/circe-json/src/main/scala/com/github/tminglei/slickpg/PgCirceJsonSupport.scala
addons/circe-json/src/test/scala/com/github/tminglei/slickpg/PgCirceJsonSupportSuite.scala
project/Build.scala

Updates circe to the most recent version (v0.6.1).

update circe to v0.6.1

---

README.md
addons/jawn/src/main/scala/com/github/tminglei/slickpg/PgJawnJsonSupport.scala
addons/jawn/src/test/scala/com/github/tminglei/slickpg/PgJawnJsonSupportSuite.scala
build.sbt

I based this on play, I needed it to try out some integration with a project using mostly Jawn (and rapture).

Support jawn JSON library

---

core/src/main/scala/com/github/tminglei/slickpg/date/PgDateJdbcTypes.scala
src/test/scala/com/github/tminglei/slickpg/PgDate2SupportSuite.scala

fix for https://github.com/tminglei/slick-pg/issues/355

fix issue 355: regression when reading OffsetDateTime values

---

addons/joda-time/src/main/scala/com/github/tminglei/slickpg/PgDateSupportJoda.scala
project/build.properties
project/plugins.sbt

This fix bug https://github.com/tminglei/slick-pg/issues/370. This regression was introduced with https://github.com/tminglei/slick-pg/commit/115e94213efd40e88f5c7923536a484dff78fd80#diff-34d5aecdb56ee5cade161615301e8560R55 (and 3 other lines that has been copy pasted from `PgDate2Support` and then edited.

Fix naming conflicts

---

README.md
build.sbt

Use the latest release for circe: https://github.com/circe/circe/releases/tag/v0.9.0

Circe 0.9.0

---

src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala

I got one mapping for LocalDate and OffsetDateTime swapped by accident.

Fix swapped tsrange and tstzrange mappings

---

core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala
core/src/test/scala/com/github/tminglei/slickpg/PgUpsertSuite.scala

This differs from iteratively calling `insertOrUpdate` because it takes
place in a single JDBC batch.
NB: This is affected by https://github.com/pgjdbc/pgjdbc/issues/783
If the JDBC connection is configured with reWriteBatchedInserts=true,
then the postgres driver will mangle the generated SQL into being
invalid. There is no workaround (other than setting 'false'), but
there's an upstream PR which fixes the bug, so the window for that to
affect things is small, and it only affects people who opt into the new
API this exposes.
I haven't been able to figure out a reasonable fallback yet for when the
capability is disabled; using DBIO.sequence(insertOrUpdate).transactionally is
reasonable for semantics but doesn't compile due to DBIOAction != ProfileAction

Add insertOrUpdateAll method for bulk upsert support.

---

core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala
core/src/test/scala/com/github/tminglei/slickpg/PgUpsertSuite.scala

Add insertOrUpdateAll method for bulk upsert support

---

src/main/scala/com/github/tminglei/slickpg/PgRangeSupport.scala

🤦‍♂️ More implicits I missed for OffsetDateTimeRange

Fix OffsetDateTimeRange implicits

---

README.md
build.sbt

Release notes: https://github.com/circe/circe/releases/tag/v0.10.1

Bump circe to 0.10.1

---

build.sbt

Follow up for https://github.com/tminglei/slick-pg/pull/478

Cross build against latest scala

---

addons/jts/src/test/scala/com/github/tminglei/slickpg/PgPostGISSupportSuite.scala
core/src/main/scala/com/github/tminglei/slickpg/geom/PgPostGISExtensions.scala

Current version lacks of these functions.

Support postgis ST_EndPoint, ST_PointN and ST_StartPoint.

---

build.sbt

Slick 3.3.3 fixes an important bug in .distinctOn

[lib] Slick 3.3.2 => 3.3.3

---

core/src/main/scala/com/github/tminglei/slickpg/str/PgStringExtensions.scala
core/src/test/scala/com/github/tminglei/slickpg/str/PgStringSupportSuite.scala

See https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP

Add support for POSIX regular expression matching on strings

---

core/src/main/scala/com/github/tminglei/slickpg/array/PgArrayJdbcTypes.scala
src/test/scala/com/github/tminglei/slickpg/PgArraySupportSuite.scala

fix generating sql for arrays with custom types

---

core/src/main/scala/com/github/tminglei/slickpg/utils/PgTokenHelper.scala
src/main/scala/com/github/tminglei/slickpg/PgCompositeSupport.scala

I have no comments, only shame

Fix token smushing performance issue

---

src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala

https://github.com/tminglei/slick-pg/pull/511 never dies
is there a postgres composite column parsing library out there somewhere? it's just insanely hard to get this right

Bug parsing arrays in composite types

---

README.md
addons/upickle-json/src/main/scala/com/github/tminglei/slickpg/PgUPickleJsonSupport.scala
addons/upickle-json/src/test/resources/logback.xml
addons/upickle-json/src/test/scala/com/github/tminglei/slickpg/PgUPickleJsonSupportSuite.scala
build.sbt

Adds support for [uPickle](https://github.com/com-lihaoyi/upickle) json library

Add uPickle json addon

---

README.md
build.sbt

added new slick-pg_play-json3 subproject which depends on play3

add support for play3
